# TFM — Predicción de huella de carbono del consumo eléctrico (España)

## Notebook 01: Carga y preparación de datos (Wattnet)

**Objetivo**: construir una serie temporal limpia de **huella de carbono operacional global** para España (ES) con resolución horaria (1h), a partir de los ficheros anuales 2022–2025.

**Resolución temporal**: los datos de Wattnet tienen resolución nativa de 15 minutos. En este trabajo se adopta resolución horaria por dos razones: (1) es la resolución estándar en la literatura de predicción de huella de carbono del mix eléctrico, facilitando la comparación con trabajos previos; (2) reduce el coste computacional de forma significativa — la serie pasa de ~140.000 a ~35.000 observaciones — manteniendo la capacidad predictiva para los horizontes de interés (48h y 72h). El resampleo se realiza tomando la media de los 4 valores de los 15 minutos anteriores a cada hora.

**Salida**:
- `df_es`: serie temporal (timestamp index) con columna `y` (objetivo) a resolución 1h.
- Conjuntos `train`, `val`, `test` por división temporal:
  - Train: 2022–2023
  - Validation: 2024
  - Test: 2025

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 140)

## 1. Configuración

Definimos la ruta base donde se encuentran las carpetas anuales (2022–2025) del dataset de Wattnet.

In [2]:
from pathlib import Path

# Definir rutas y constantes
BASE_PATH = Path("/home/ubuntu/TFM")
DATA_RAW = BASE_PATH / "data_raw"

YEAR_FOLDERS = [
    "2022",
    "2023",
    "2024",
    "2025",
]

TARGET_FILE = Path("footprints") / "carbon_footprint_operational_global.csv"

COUNTRY_CODE = "ES"  # Spain
TIME_COL = "timestamp"

In [3]:
from pathlib import Path
PROJECT_ROOT = Path.cwd().parents[0]  
DATA_RAW = PROJECT_ROOT / "data_raw"

In [4]:
# Comprobar que los ficheros objetivo existen
paths = [DATA_RAW / y / TARGET_FILE for y in YEAR_FOLDERS]

missing = [str(p) for p in paths if not p.exists()]
if missing:
    raise FileNotFoundError(
        "No se han encontrado estos ficheros:\n" + "\n".join(missing) +
        "\n\nRevisa DATA_RAW, YEAR_FOLDERS o TARGET_FILE."
    )

paths

[PosixPath('/home/ubuntu/TFM/data_raw/2022/footprints/carbon_footprint_operational_global.csv'),
 PosixPath('/home/ubuntu/TFM/data_raw/2023/footprints/carbon_footprint_operational_global.csv'),
 PosixPath('/home/ubuntu/TFM/data_raw/2024/footprints/carbon_footprint_operational_global.csv'),
 PosixPath('/home/ubuntu/TFM/data_raw/2025/footprints/carbon_footprint_operational_global.csv')]

## 2. Lectura de ficheros y concatenación

Se cargan los datos de huella de carbono operacional global. Los ficheros originales de Wattnet contienen timestamps a resolución de 15 minutos, resultado de una interpolación sobre datos horarios nativos. En el paso de reindexado (sección 4) se remuestrea la serie a resolución horaria mediante resampleo a la media, recuperando así la resolución real de los datos subyacentes.

Cada CSV contiene una columna `timestamp` y una columna por país.
Se selecciona únicamente `timestamp` y la columna `ES`.
España se elige como caso de estudio por la disponibilidad de datos completos y la diversidad de su mix energético.

In [5]:
def load_country_series(csv_path: Path, time_col: str, country_col: str) -> pd.DataFrame:
    """
    Lee un CSV de Wattnet con columnas: timestamp, AT, BA, ..., ES, ...
    Devuelve DataFrame con columnas: timestamp, y (float)
    """
    df = pd.read_csv(csv_path, usecols=[time_col, country_col])
    
    # Parseo de tiempo
    df[time_col] = pd.to_datetime(df[time_col], errors="raise", utc=True)
    
    # Renombrar objetivo
    df = df.rename(columns={country_col: "y"})
    
    # Asegurar tipo numérico
    df["y"] = pd.to_numeric(df["y"], errors="coerce")
    
    return df

In [6]:
dfs = []
for p in paths:
    df_part = load_country_series(p, TIME_COL, COUNTRY_CODE)
    dfs.append(df_part)

df_es = pd.concat(dfs, ignore_index=True)

df_es.head(), df_es.shape

(                  timestamp       y
 0 2022-01-01 00:00:00+00:00  120.79
 1 2022-01-01 00:15:00+00:00  120.79
 2 2022-01-01 00:30:00+00:00  120.79
 3 2022-01-01 00:45:00+00:00  120.80
 4 2022-01-01 01:00:00+00:00  120.04,
 (140256, 2))

## 3. Limpieza y formateo

- Ordenar por tiempo
- Establecer `timestamp` como índice
- Comprobar valores nulos en `y`

In [7]:
df_es = df_es.sort_values(TIME_COL)

# Duplicados exactos de timestamp no deberían existir, pero por si acaso los contamos y eliminamos
n_dupes = df_es.duplicated(subset=[TIME_COL]).sum()
print("Duplicados de timestamp:", n_dupes)

if n_dupes > 0:
    df_es = df_es.drop_duplicates(subset=[TIME_COL], keep="first")

df_es = df_es.set_index(TIME_COL)
df_es = df_es.sort_index()

df_es.info()

Duplicados de timestamp: 0
<class 'pandas.DataFrame'>
DatetimeIndex: 140256 entries, 2022-01-01 00:00:00+00:00 to 2025-12-31 23:45:00+00:00
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   y       140244 non-null  float64
dtypes: float64(1)
memory usage: 2.1 MB

In [8]:
missing_y = df_es["y"].isna().sum()
total = len(df_es)
print(f"Nulos en y: {missing_y} ({missing_y/total:.4%})")

df_es.describe()

Nulos en y: 12 (0.0086%)

                   y
count  140244.000000
mean      114.354448
std        48.763052
min        31.850000
25%        73.950000
50%       107.590000
75%       147.720000
max       281.850000

## 4. Comprobación de frecuencia temporal y resampleo a 1h

Los datos originales tienen resolución de 15 minutos. Se verifica la continuidad temporal y se remuestrea a resolución horaria tomando la media de los 4 valores de los 15 minutos anteriores a cada hora (`label="right"`, `closed="right"`). Este resampleo es metodológicamente correcto para la huella de carbono — el valor de la hora representa el promedio de la actividad del sistema eléctrico durante ese periodo.

In [9]:
deltas = df_es.index.to_series().diff().dropna()
mode_delta = deltas.mode().iloc[0]
print("Delta más común:", mode_delta)
print(deltas.value_counts().head(5))
expected = pd.Timedelta(minutes=15)
gaps = (deltas > expected).sum()
print("Número de saltos > 15 min:", gaps)

Delta más común: 0 days 00:15:00
timestamp
0 days 00:15:00    140255
Name: count, dtype: int64
Número de saltos > 15 min: 0

In [10]:
# Resampleo a 1h — media de los 4 valores de 15 min anteriores a cada hora
df_es = df_es.resample("1h", label="right", closed="right").mean()

full_index = pd.date_range(
    start=df_es.index.min(),
    end=df_es.index.max(),
    freq="1h",
    tz="UTC"
)
df_es = df_es.reindex(full_index)
df_es.index.name = "timestamp"

print("Filas tras resampleo y reindexado:", len(df_es))
print("Nulos tras reindexado:", df_es["y"].isna().sum())
df_es.head()

Filas tras resampleo y reindexado: 35065
Nulos tras reindexado: 0

                                  y
timestamp
2022-01-01 00:00:00+00:00  120.7900
2022-01-01 01:00:00+00:00  120.6050
2022-01-01 02:00:00+00:00  120.8400
2022-01-01 03:00:00+00:00  123.1475
2022-01-01 04:00:00+00:00  123.0475

La serie queda con resolución horaria regular. Los posibles huecos tras el reindexado se imputarán en el siguiente paso mediante interpolación temporal.

In [11]:
train = df_es.loc["2022-01-01":"2023-12-31 23:59:59"]
val   = df_es.loc["2024-01-01":"2024-12-31 23:59:59"]
test  = df_es.loc["2025-01-01":"2025-12-31 23:59:59"]

print("Train:", train.shape, "NaNs:", train["y"].isna().sum())
print("Val:  ", val.shape,   "NaNs:", val["y"].isna().sum())
print("Test: ", test.shape,  "NaNs:", test["y"].isna().sum())

Train: (17520, 1) NaNs: 0
Val:   (8784, 1) NaNs: 0
Test:  (8760, 1) NaNs: 0

## 5. Imputación de valores faltantes

Dado que el porcentaje de valores faltantes es muy bajo tras el resampleo, realizamos imputación mediante interpolación temporal para mantener una rejilla horaria regular.

In [12]:
df_es["y"] = df_es["y"].interpolate(method="time")

print("Filas tras interpolación:", len(df_es))
print("Nulos tras interpolación:", df_es["y"].isna().sum())
df_es.head()

Filas tras interpolación: 35065
Nulos tras interpolación: 0

                                  y
timestamp
2022-01-01 00:00:00+00:00  120.7900
2022-01-01 01:00:00+00:00  120.6050
2022-01-01 02:00:00+00:00  120.8400
2022-01-01 03:00:00+00:00  123.1475
2022-01-01 04:00:00+00:00  123.0475

In [13]:
# Ver si hay valores nulos
print("Valores nulos por columna:")
df_es.isnull().sum()

Valores nulos por columna:

y    0
dtype: int64

## 6. División temporal Train / Validation / Test

Se utiliza una división temporal para evitar fuga de información:

- **Train**: 2022–2023  
- **Validation**: 2024  
- **Test**: 2025  

Esta estrategia permite seleccionar hiperparámetros en validación y reportar resultados finales en test. Los datos se encuentran a resolución horaria (1h).

In [14]:
train = df_es.loc["2022-01-01":"2023-12-31 23:59:59"]
val   = df_es.loc["2024-01-01":"2024-12-31 23:59:59"]
test  = df_es.loc["2025-01-01":"2025-12-31 23:59:59"]

print("Train:", train.shape, "NaNs:", train["y"].isna().sum())
print("Val:  ", val.shape,   "NaNs:", val["y"].isna().sum())
print("Test: ", test.shape,  "NaNs:", test["y"].isna().sum())

Train: (17520, 1) NaNs: 0
Val:   (8784, 1) NaNs: 0
Test:  (8760, 1) NaNs: 0

## 7. Guardado de datos procesados (intermedio)

Guardamos en formato eficiente para acelerar el trabajo posterior (EDA/modelos).  
Formato recomendado: **Parquet**.

In [15]:
from pathlib import Path

OUT_DIR = Path("data_processed")
OUT_DIR.mkdir(exist_ok=True)

df_es.to_parquet(OUT_DIR / "es_carbon_footprint_operational_global_1h_2022_2025.parquet")
train.to_parquet(OUT_DIR / "train_2022_2023.parquet")
val.to_parquet(OUT_DIR / "val_2024.parquet")
test.to_parquet(OUT_DIR / "test_2025.parquet")

print("Guardado en:", OUT_DIR.resolve())
print(f"Serie completa: {len(df_es)} filas (resolución 1h)")
print(f"Train: {len(train)} | Val: {len(val)} | Test: {len(test)}")

Guardado en: /home/ubuntu/TFM/notebooks/data_processed
Serie completa: 35065 filas (resolución 1h)
Train: 17520 | Val: 8784 | Test: 8760